name: 'Setup Maven'
description: 'Install a specific version of Apache Maven and add it to the PATH'
author: 'stCarolas'
inputs:
  maven-version:
    description: 'Version Spec of the version to use.  Examples: 10.x, 10.15.1, >=10.15.0'
    default: '3.8.2'
  maven-mirror:
    description: 'download mirror,url or aliyun or empty'
    default: ''
runs:
  using: 'node20'
  main: 'lib/setup-maven.js'
